### ISSUE TITLE
:) 

### ISSUE THREAD

**Issue by rochacbruno** [danielvolponi/python-base#1]
O exercício está correto! você aplicou o dicionário corretamente no lugar da lista de tuplas!

Nesta parte aqui:

https://github.com/danielvolponi/python-base/blob/8cb649348e0611221b04bdb978a5f71eca041329/escola_v3_com_dict.py#L9-L16

Daria para fazer algo do tipo:

```py
dados = {
   "salas": {
        "sala1": [.....],
	    "sala2": [.....],
    },
   "atividades": {
        "ingles": [.....],
	    "musica": [.....],
    },
}
```

Mas só para exercitar o uso de diversos niveis de aninhamento nos dicts,

**Comment by danielvolponi** [comment]
Muito obrigado Bruno!! Vou tentar fazer dessa forma!
